name: Create Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: google-services.json and extra strings file
        env:
          GOOGLE_SERVICES_BASE64: ${{secrets.GOOGLE_SERVICES_BASE64}}
          STRINGS_OTHER_BASE64: ${{secrets.STRINGS_OTHER}}
        run: |
          echo $GOOGLE_SERVICES_BASE64 | base64 --decode > ./app/google-services.json
          echo $STRINGS_OTHER_BASE64 | base64 --decode > ./app/src/main/res/values/strings_other.xml

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > release-keystore.jks

      - name: Build signed APK
        env:
          RELEASE_KEYSTORE_PATH: ${{ github.workspace }}/release-keystore.jks
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Get commit messages since last release
        id: get_commits
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          echo "Last tag: $LAST_TAG"
          if [ -z "$LAST_TAG" ]; then
            echo "No previous tag found. Getting all commits."
            git log --pretty=format:'%h %s' > commits.txt
          else
            echo "Previous tag: $LAST_TAG"
            git log "$LAST_TAG"..HEAD --pretty=format:'%h %s' > commits.txt
          fi

      - name: Set release notes
        id: set_release_notes
        run: |
          RELEASE_NOTES=$(awk '{printf "%s%%0A", $0}' commits.txt)
          RELEASE_NOTES="${RELEASE_NOTES%\\%0A}"
          RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\r'/'%0D'}"
          echo "release_notes=$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "Release Notes: $RELEASE_NOTES"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.set_release_notes.outputs.release_notes }}
          draft: false
          prerelease: false

      - name: Set APK asset path without 'v' prefix
        id: set_apk_path
        run: |
          APK_NAME="ImmichTV-${GITHUB_REF_NAME#v}.apk"
          echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT
          echo "apk_path=app/build/outputs/apk/release/$APK_NAME" >> $GITHUB_OUTPUT
          echo "APK Name: $APK_NAME"
          echo "APK Path: app/build/outputs/apk/release/$APK_NAME"

      - name: Upload APK Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.set_apk_path.outputs.apk_path }}
          asset_name: ${{ steps.set_apk_path.outputs.apk_name }}
          asset_content_type: application/vnd.android.package-archive
